import  $ from 'jquery'// подключение к файлу библиотеки jquery
import './index.css'
import './index.sass'
import './modules/navBurger/navBurger.js'
import './modules/impressions-room/impressions-room.js'
import './modules/mixin-dropdown-wide/dropdown-wide-table.js'
import './modules/mixin-checkbox-buttons/checkbox-buttons.js'
import './modules/dropdown-less/dropdown-less-table.js'
import './modules/expandable-checkbox-list/expandable-checkbox-list.js'
import './modules/card-slider-main/card-slider-main.js'
import './modules/pagination/pagination.js'
import './modules/range-slider/range-slider.js'
import './modules/calendar/calendar.js'
import './modules/filter-date-dropdown-input/filter-date-dropdown.js'
